Created Admin UI
microsoftgraph/aspnet-assettracking-sample pull request #15
Opened 2019-07-09 09:17 UTC by ElinorW

Administrator's views with static content. No database connection.

2019-07-09 11:33 UTC, titusgicheru requested changes
- Please have **OfficeBooks** and **OfficeItems** in their own controllers Views
- While the UI looks great on the Desktop browser, consider making it responsive. Tables may not be the best approach to achieve responsiveness.

2019-07-10 07:17 UTC, irvinesunday reviewed
![isbn toggle](https://user-images.githubusercontent.com/40403681/60948267-36b78a80-a2fb-11e9-940b-56c189eccd88.PNG)

I can't think of any use case for needing to have the `Book ISBN` toggle-able to display items in ascending or descending order (based on their ISBN). I think we can remove this one feature. Same applies to the Office Items `Description` as shown below.

![description](https://user-images.githubusercontent.com/40403681/60950696-4e454200-a300-11e9-9f05-4e4836744961.PNG)

2019-07-10 07:26 UTC, irvinesunday commented
![responsive_tables](https://user-images.githubusercontent.com/40403681/60948714-41265400-a2fc-11e9-880f-85554ead677d.PNG)

@titusgicheru I think the tables handle responsiveness quite okay in different window sizes. It's just the `Borrowed Items` and `Borrowed Books` table that struggle a little when their window sizes are pushed to their minimum size. @ElinorW please check this out.

2019-07-10 07:44 UTC, irvinesunday commented on AssetTracking/AssetTracking/Views/Home/OfficeBooks.cshtml
> +                        <td><a asp-controller="Home" asp-action="ViewBookLog"> View Book Log </a>|
`View History` sounds more descriptive.

2019-07-10 07:54 UTC, irvinesunday commented on AssetTracking/AssetTracking/Views/Home/OfficeBooks.cshtml
> +                        </td>
Can we also add a `View Details` link here for each of the list of Book Items.

2019-07-10 08:02 UTC, irvinesunday commented
Consider adding the following:
- **Name** of the signed-in user and role (e.g Administrator)
- Quick snapshot of the running **total** of the items in each table category for both Office Books and Office Items
- An **overdue warning icon** (e.g. an exclamation mark) next to overdue items/books just before the `Send Reminder` button as below. 
![reminder](https://user-images.githubusercontent.com/40403681/60951556-150dd180-a302-11e9-8da5-82cc055a99a5.PNG)

2019-07-10 09:28 UTC, titusgicheru commented
> ![responsive_tables](https://user-images.githubusercontent.com/40403681/60948714-41265400-a2fc-11e9-880f-85554ead677d.PNG)
> 
> @titusgicheru I think the tables handle responsiveness quite okay in different window sizes. It's just the `Borrowed Items` and `Borrowed Books` table that struggle a little when their window sizes are pushed to their minimum size. @ElinorW please check this out.

@irvinesunday I think if we want to achieve responsiveness in the UI,  using tables is generally not a good idea. It's better not to use tables unless we explicitly want data to be laid out in rows and columns and in this scenarios we are most likely going to trade off responsiveness.

2019-07-11 14:26 UTC, ElinorW commented
I've updated the files. 
Made the requested changes, still working on adding the following
- Name of the signed-in user and role (e.g Administrator)
- An overdue warning icon (e.g. an exclamation mark) next to overdue items/books just before the send reminder button.

2019-07-12 07:17 UTC, merged