Ns/integration to sharepoint
microsoftgraph/aspnet-assettracking-sample pull request #20
Opened 2019-08-13 08:07 UTC by nicolesigei

Adds feature #5 
**Features proposed in this pull request**
Integrating the app to SharePoint to retrieve properties and relationship for a site resource and to return metadata for an item in a list. Using CRUD functions in a repository class that are injected in the controllers.

2019-08-14 07:36 UTC, titusgicheru requested changes

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Controllers/OfficeBooksController.cs
>          [Route("")]
Remove this attribute if not in use.

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Controllers/OfficeBooksController.cs
>              return View("~/Views/Admin/OfficeBooks.cshtml");
Is there a reason why we are explicitly redirecting to the same view? And is this the best approach?

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Controllers/OfficeBooksController.cs
> +            ViewBag.List = officeBook;
Consider returning a List of **OfficeBook** as opposed to using a **ViewBag**

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Controllers/OfficeBooksController.cs
> +            return result;
Perhaps redirect to **GetBooks()** which returns a list of all books.

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Controllers/OfficeBooksController.cs
> +            return result;
Redirect to a List of all books or to a details View.

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Controllers/OfficeItemsController.cs
> +            ViewBag.List = _officeItemRepository;
Here also consider returning a List of **OfficeItem** as opposed to using a **ViewBag**

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Models/OfficeBookRepository.cs
> +        private readonly string siteId = "m365b267815.sharepoint.com,6e1261a1-6d03-432a-95c0-e1c7705aef5f,f43d258c-ece0-476a-a1c0-018d359817d5";
This should not be hard coded have the **siteId** in a settings file.

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Models/OfficeBookRepository.cs
> +                var _officeBookList = sharePointLists.Where(x => x.DisplayName.Contains("Office Books")).FirstOrDefault();
Avoid using **inference**, replace all **var** keywords with actual return **types**. This applies to all references in this file.

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Models/OfficeItem.cs
> +
Remove white space

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Models/OfficeItemRepository.cs
> +
Remove white space.

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Models/OfficeItemRepository.cs
> +
Remove white space.

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Models/OfficeItemRepository.cs
> +
Remove white space.

2019-08-14 07:36 UTC, titusgicheru commented on AssetTracking/AssetTracking/Models/OfficeItemRepository.cs
> +        private readonly string siteId = "m365b267815.sharepoint.com,6e1261a1-6d03-432a-95c0-e1c7705aef5f,f43d258c-ece0-476a-a1c0-018d359817d5";
Avoid hard coding values. Store in config file instead.

2019-08-19 13:33 UTC, irvinesunday commented on AssetTracking/AssetTracking/Models/OfficeBookRepository.cs
> +        public GraphServiceClient GraphClient { get; private set; }
Do we really need this property?

2019-08-20 07:40 UTC, irvinesunday requested changes

2019-08-20 07:40 UTC, irvinesunday commented on AssetTracking/AssetTracking/Models/OfficeBookRepository.cs
> +        private readonly string itemId = null;
This field is not used; you can remove it.

2019-08-20 07:40 UTC, irvinesunday commented on AssetTracking/AssetTracking/Models/OfficeBookRepository.cs
> +                var _officeBookList = sharePointLists.Where(x => x.DisplayName.Contains("Office Books")).FirstOrDefault();
Additionally, let's maintain uniform variable naming conventions throughout. Preferably an '_' prefixing a field name (followed by camelCasing) for private fields and then camelCase for all method variables.

2019-08-20 07:40 UTC, irvinesunday commented on AssetTracking/AssetTracking/Models/OfficeBookRepository.cs
> +                var _officeBookList = sharePointLists.Where(b => b.DisplayName.Contains("Office Books")).FirstOrDefault();
You can have the "Office Books" defined as a const field data, e.g.
`private const string OfficeBooksDisplayName = "Office Books";`
And then use this across the file where you are checking for the book's display name property.

2019-09-05 08:02 UTC, merged